import type { Property } from "@/lib/types";

export const LOCATIONS = [
  "Lekki",
  "Victoria Island",
  "Ikoyi",
  "Ajah",
  "Ikeja",
  "Yaba",
  "Chevron",
  "Sangotedo",
] as const;

export const seedProperties: Property[] = [
  {
    id: "ph-001",
    title: "Waterfront Residence on Admiralty Drive",
    slug: "waterfront-residence-admiralty-drive-lekki",
    description:
      "A quiet four-bedroom home set back from Admiralty Drive, with rooms that open onto a long garden and a terrace that stays cool in the late afternoon. Finished in 2023 and occupied by a single family since.",
    price: 485000000,
    location: "Lekki",
    address: "14 Admiralty Drive, Lekki Phase 1, Lagos",
    propertyType: "House",
    listingType: "For Sale",
    bedrooms: 4,
    bathrooms: 5,
    squareFeet: 4200,
    amenities: ["Swimming pool", "Generator", "24-hour security", "Parking for 4", "Staff quarters"],
    features: ["Lagoon-facing terrace", "Walk-in closet", "Fitted kitchen", "Study"],
    featured: true,
    status: "Available",
    agentName: "Amaka Obi",
    agentPhone: "+234 803 441 2290",
    agentEmail: "amaka@propertyhub.ng",
    createdAt: "2026-06-12",
    images: [
      { id: "i1", url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1800&q=80", alt: "Waterfront house exterior", isPrimary: true },
      { id: "i2", url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80", alt: "Living room", isPrimary: false },
    ],
  },
  {
    id: "ph-002",
    title: "Two-Bedroom Apartment on Kofo Abayomi",
    slug: "two-bedroom-apartment-kofo-abayomi-vi",
    description:
      "A high-floor apartment in a well-kept block on Kofo Abayomi Street. Both bedrooms are en-suite. The living room has a long balcony toward the lagoon edge of Victoria Island.",
    price: 8500000,
    location: "Victoria Island",
    address: "27 Kofo Abayomi Street, Victoria Island, Lagos",
    propertyType: "Apartment",
    listingType: "For Rent",
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1450,
    amenities: ["Lift", "Generator", "Security", "Parking for 2"],
    features: ["Balcony", "En-suite bedrooms", "Fitted wardrobes"],
    featured: true,
    status: "Available",
    agentName: "Tunde Balogun",
    agentPhone: "+234 809 112 8834",
    agentEmail: "tunde@propertyhub.ng",
    createdAt: "2026-07-02",
    images: [
      { id: "i3", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1800&q=80", alt: "Bright apartment", isPrimary: true },
    ],
  },
  {
    id: "ph-003",
    title: "Family Duplex in Old Ikoyi",
    slug: "family-duplex-old-ikoyi",
    description:
      "A five-bedroom duplex on a quiet street in Old Ikoyi. Mature trees, a small pool, oak floors, and a self-contained unit at the back. Title is clean. Inspection by appointment.",
    price: 920000000,
    location: "Ikoyi",
    address: "8 Glover Road, Old Ikoyi, Lagos",
    propertyType: "Duplex",
    listingType: "For Sale",
    bedrooms: 5,
    bathrooms: 6,
    squareFeet: 6100,
    amenities: ["Swimming pool", "Generator", "Security", "Staff quarters", "Garden"],
    features: ["Formal dining", "Family lounge", "Walk-in pantry"],
    featured: true,
    status: "Available",
    agentName: "Amaka Obi",
    agentPhone: "+234 803 441 2290",
    agentEmail: "amaka@propertyhub.ng",
    createdAt: "2026-05-18",
    images: [
      { id: "i4", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1800&q=80", alt: "Duplex in a garden", isPrimary: true },
    ],
  },
  {
    id: "ph-004",
    title: "Corner Plot near Abraham Adesanya",
    slug: "corner-plot-abraham-adesanya-ajah",
    description:
      "A dry rectangular corner plot in Ajah, a short drive from Abraham Adesanya. Fenced on two sides and above the usual flood line. Survey papers available before payment.",
    price: 65000000,
    location: "Ajah",
    address: "Off Abraham Adesanya Road, Ajah, Lagos",
    propertyType: "Land",
    listingType: "For Sale",
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 7200,
    amenities: ["Fenced", "Corner plot", "Motorable access"],
    features: ["Dry land", "Survey available"],
    featured: false,
    status: "Available",
    agentName: "Chidi Eze",
    agentPhone: "+234 802 667 1904",
    agentEmail: "chidi@propertyhub.ng",
    createdAt: "2026-08-01",
    images: [
      { id: "i5", url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1800&q=80", alt: "Open residential land", isPrimary: true },
    ],
  },
  {
    id: "ph-005",
    title: "Three-Bedroom Flat in GRA Ikeja",
    slug: "three-bedroom-flat-gra-ikeja",
    description:
      "A ground-floor flat in a four-unit house on a residential street in Ikeja GRA. Large rooms, a private backyard, and parking inside the compound. Annual rent; service charge separate.",
    price: 6500000,
    location: "Ikeja",
    address: "11 Isaac John Street, GRA Ikeja, Lagos",
    propertyType: "Apartment",
    listingType: "For Rent",
    bedrooms: 3,
    bathrooms: 3,
    squareFeet: 1800,
    amenities: ["Compound parking", "Security", "Water borehole"],
    features: ["Private backyard", "All rooms en-suite"],
    featured: true,
    status: "Available",
    agentName: "Tunde Balogun",
    agentPhone: "+234 809 112 8834",
    agentEmail: "tunde@propertyhub.ng",
    createdAt: "2026-07-21",
    images: [
      { id: "i6", url: "https://images.unsplash.com/photo-1560184897-ae75f418493e?auto=format&fit=crop&w=1800&q=80", alt: "Ikeja apartment interior", isPrimary: true },
    ],
  },
  {
    id: "ph-006",
    title: "Studio Loft near Yaba Tech",
    slug: "studio-loft-near-yaba-tech",
    description:
      "A compact studio on a renovated floor a short walk from Yaba College of Technology. High ceilings, good light, and a usable kitchenette.",
    price: 2200000,
    location: "Yaba",
    address: "Herbert Macaulay Way, Yaba, Lagos",
    propertyType: "Apartment",
    listingType: "For Rent",
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 520,
    amenities: ["Security", "Prepaid meter"],
    features: ["High ceilings", "Kitchenette"],
    featured: false,
    status: "Available",
    agentName: "Chidi Eze",
    agentPhone: "+234 802 667 1904",
    agentEmail: "chidi@propertyhub.ng",
    createdAt: "2026-08-14",
    images: [
      { id: "i7", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1800&q=80", alt: "Studio loft", isPrimary: true },
    ],
  },
  {
    id: "ph-007",
    title: "Four-Bedroom House in Chevron Drive",
    slug: "four-bedroom-house-chevron-drive",
    description:
      "A detached four-bedroom house on a gated street off Chevron Drive. Living and dining downstairs, bedrooms upstairs, space for three cars.",
    price: 310000000,
    location: "Chevron",
    address: "Chevron Drive, Lekki, Lagos",
    propertyType: "House",
    listingType: "For Sale",
    bedrooms: 4,
    bathrooms: 4,
    squareFeet: 3400,
    amenities: ["Gated street", "Generator", "Security", "Parking for 3"],
    features: ["All rooms en-suite", "Fitted kitchen"],
    featured: true,
    status: "Available",
    agentName: "Amaka Obi",
    agentPhone: "+234 803 441 2290",
    agentEmail: "amaka@propertyhub.ng",
    createdAt: "2026-06-28",
    images: [
      { id: "i8", url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1800&q=80", alt: "Detached house", isPrimary: true },
    ],
  },
  {
    id: "ph-008",
    title: "Retail Unit on the Sangotedo Axis",
    slug: "retail-unit-sangotedo-axis",
    description:
      "A ground-floor commercial bay on a busy stretch of the Sangotedo corridor. Wide frontage, small rear store, and a toilet. Three-year lease.",
    price: 4800000,
    location: "Sangotedo",
    address: "Lekki-Epe Expressway, Sangotedo, Lagos",
    propertyType: "Commercial",
    listingType: "For Rent",
    bedrooms: 0,
    bathrooms: 1,
    squareFeet: 980,
    amenities: ["Road frontage", "Shared generator"],
    features: ["Wide shopfront", "Rear store"],
    featured: false,
    status: "Available",
    agentName: "Tunde Balogun",
    agentPhone: "+234 809 112 8834",
    agentEmail: "tunde@propertyhub.ng",
    createdAt: "2026-08-20",
    images: [
      { id: "i9", url: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1800&q=80", alt: "Retail interior", isPrimary: true },
    ],
  },
  {
    id: "ph-009",
    title: "Penthouse on Lekki Conservation Road",
    slug: "penthouse-lekki-conservation-road",
    description:
      "The top two floors of a six-storey building combined into one residence. Open living floor facing west, three bedrooms above, and a small roof terrace.",
    price: 17500000,
    location: "Lekki",
    address: "Lekki Conservation Road, Lekki, Lagos",
    propertyType: "Apartment",
    listingType: "For Rent",
    bedrooms: 3,
    bathrooms: 4,
    squareFeet: 3100,
    amenities: ["Lift", "Basement parking", "Generator", "Gym"],
    features: ["Roof terrace", "Walk-in closet"],
    featured: true,
    status: "Available",
    agentName: "Amaka Obi",
    agentPhone: "+234 803 441 2290",
    agentEmail: "amaka@propertyhub.ng",
    createdAt: "2026-04-30",
    images: [
      { id: "i10", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1800&q=80", alt: "Penthouse at dusk", isPrimary: true },
    ],
  },
  {
    id: "ph-010",
    title: "Semi-Detached Duplex in Sangotedo Estate",
    slug: "semi-detached-duplex-sangotedo-estate",
    description:
      "A four-bedroom semi-detached house inside a managed estate in Sangotedo. Single gate, small playground, unused kitchen, compact BQ.",
    price: 145000000,
    location: "Sangotedo",
    address: "Greenfield Estate, Sangotedo, Lagos",
    propertyType: "Duplex",
    listingType: "For Sale",
    bedrooms: 4,
    bathrooms: 4,
    squareFeet: 2800,
    amenities: ["Estate security", "Playground", "Generator", "BQ"],
    features: ["Brand new", "All rooms en-suite"],
    featured: false,
    status: "Available",
    agentName: "Chidi Eze",
    agentPhone: "+234 802 667 1904",
    agentEmail: "chidi@propertyhub.ng",
    createdAt: "2026-07-09",
    images: [
      { id: "i11", url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1800&q=80", alt: "Semi-detached duplex", isPrimary: true },
    ],
  },
];
